version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

services:

  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    logging: *default-logging
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${ROOT}/npm-data:/data
      - ${ROOT}/letsencrypt:/etc/letsencrypt
      - &resolv './resolv.conf:/etc/resolv.conf'
    networks:
      - redonda

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    ports:
      - "9091:9091"
    volumes:
      - ${ROOT}/downloads:/downloads # where transmission will store the data
      - ${ROOT}/config/transmission-vpn:/config # where transmission-home is stored
      - *resolv
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=us_washington_dc
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=US
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - VPN_LOG_LEVEL=11
      - PEER_DNS=false
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/downloads
      - TRANSMISSION_WATCH_DIR=/downloads
      - TRANSMISSION_WATCH_DIR_ENABLED=false

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - "9117:9117"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
      - './resolv.conf:/etc/resolv.conf'

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - "6789:6789"
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
      - './resolv.conf:/etc/resolv.conf'

  plex-server:
    container_name: plex-server
      #image: plexinc/pms-docker:latest
    image: linuxserver/plex:latest
    restart: unless-stopped
    logging: *default-logging
    environment:
      - TZ=${TZ} # timezone, defined in .env
    networks:
      - redonda
    ports:
      - "32400:32400"
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
      - './resolv.conf:/etc/resolv.conf'

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    logging: *default-logging
    networks:
      - redonda
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767

networks:
  redonda:
    driver: bridge
